### ISSUE TITLE
Make some visual options easily customizable

### ISSUE THREAD

**Issue by LoicGoyet** [Victoire/WidgetButtonBundle#20]
Today some visual options like the button size or the button theme is a list of static options that we cannot increase or decrease with new value.

But some designs requires only two themes, and some other four button sizes. So today we need to share with the team that some button themes are available but not to pick, and make some custom themes for new sizes. This is a kind of boring experience for both users and developers.

The idea is to make customizable the list of options available to the front form, with some configuration on this model :

```yml
widget_button:
  sizes:
    xs: 'widget.button.form.choice.size.extrasmall'
    sm: 'widget.button.form.choice.size.small'
    md: 'widget.button.form.choice.size.medium'
    lg: 'widget.button.form.choice.size.large'
  themes:
    default: 'widget.button.form.choice.theme.default'
    primary: 'widget.button.form.choice.theme.primary'
    ...
```

This would give to the developers the possibility to increase default behavior and setup more restrictive guidelines. User would not be as confused about the usage of themes or widget-edit for similar visual feature
